version: '3'

services:
    baza_webserver:
        build:
            context: ./docker/config/webserver
        restart: 'always'
        container_name: 'baza_web'
        ports:
            - "8888:80"
        volumes:
            - ./app:/var/www/html
            - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/config/webserver/vhost:/etc/apache2/sites-enabled
            - ./docker/storage/logs/apache2:/var/log/apache2
        links:
            - baza_mysql
        depends_on:
            - baza_mysql

    baza_mysql:
        build: ./docker/config/mysql
        container_name: 'baza_mysql'
        restart: 'always'
        hostname: 'baza_mysql'
        volumes:
            - ./docker/storage/mysql:/var/lib/mysql
            - ./docker/storage/logs/mysql:/var/log/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=baza
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        ports:
            - "3306:3306"

    baza_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'baza_phpmyadmin'
        links:
            - baza_mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - '8080:80'
        volumes:
            - /sessions
