version: '3'

services:
  php:
    image: hub.t-me.pp.ua/wi1w/webserver:for-bonum
    restart: 'always'
    command: bash -c 'cp /page.speed /etc/apache2/page.speed && sed -i -- "s~{ORIGIN}~${DOMAIN}~g" /etc/apache2/page.speed && chown -R 500:500 /var/www/html/ && . /etc/apache2/envvars; /usr/sbin/apache2 -DFOREGROUND'
    volumes:
      - ./config/vhosts/page.speed:/page.speed
      - ./config/vhosts/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./config/vhosts/geoip.conf:/etc/apache2/mods-available/geoip.conf
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/apache2:/var/log/apache2
    links:
      - mariadb
    depends_on:
      - mariadb
      - migration
    networks:
      - frontend
      - backend
    labels:
      - 'traefik.backend=stage_7vigod'
      - 'traefik.frontend.rule=Host:${DOMAIN},www.${DOMAIN}'
      - 'traefik.docker.network=frontend'
      - 'traefik.port=80'
      - 'traefik.frontend.redirect.permanent=true'
      - "traefik.frontend.redirect.regex=^https://www.${DOMAIN}/(.*)$$"
      - "traefik.frontend.redirect.replacement=https://${DOMAIN}/$$1"

  migration:
    image: hub.t-me.pp.ua/wi1w/webserver:for-bonum
    restart: on-failure
    command: bash -c 'chmod +x /var/www/html/migrate.sh && bash /var/www/html/migrate.sh'
    volumes:
      - ./www:/var/www/html
      - ./migrate.sh:/var/www/html/migrate.sh
    links:
      - mariadb
    depends_on:
      - mariadb
    networks:
      - backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_API: ${DOMAIN_API}
    labels:
      - 'traefik.enable=false'

  mariadb:
    image: mariadb:10.3
    restart: 'always'
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /docker-entrypoint.sh mysqld --log-error=/var/log/mysql/err.log --general-log=1 --general-log-file=/var/log/mysql/general-log.log --character-set-server=utf8 --collation-server=utf8_general_ci"
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./db/bcp.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
    labels:
      - 'traefik.enable=false'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    volumes:
      - /sessions
    labels:
      - 'traefik.backend=stage_phpmyadmin'
      - 'traefik.frontend.rule=Host:${DOMAIN};PathPrefixStrip:/phpmyadmin/'
      - 'traefik.docker.network=frontend'
      - 'traefik.port=80'
      - 'traefik.frontend.auth.basic=${AUTH}'

  backup:
    image: hub.t-me.pp.ua/wi1w/docker-mysql-backup:latest
    links:
      - mariadb
    networks:
      - backend
    volumes:
      - ./backups:/backup
    environment:
      DBS: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
      RSYNC_COMMAND: "cp %DIR%/* /backup"
      CRON_TIME: "0 0 * * *"
      NOTIFICATION_SERVICE: slack
      SLACK_HOOK_URL: "https://hooks.slack.com/services/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"
      SLACK_CHANNEL: "#devtalk"
      SLACK_USERNAME: "mysql-backup"
      SLACK_EMOJI: "package"
    labels:
      - "traefik.enable=false"

  logrotate:
    image: blacklabelops/logrotate
    networks:
      - backend
    volumes:
      - ./logs:/var/log/docker
    environment:
      LOGS_DIRECTORIES: "/var/log/docker"
      LOGROTATE_SIZE: 10M
      LOGROTATE_CRONSCHEDULE: "* */1 * * *"
      LOGROTATE_COMPRESSION: compress
      LOGROTATE_MAXAGE: 60
      LOGROTATE_MINSIZE: 10M
    labels:
      - 'traefik.enable=false'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
      
networks:
  frontend:
    external: true
  backend:
    external: false
