<?php
return [
    'emptyComing' => [
        'id' => 1,
        'transaction' => 100384,
        'old_value' => null,
        'whence' => 2,
        'where' => 1,
        'prod_value' => null,
        'status' => 0,
        'type' => 1,
        'date' => '2019-05-30 16:38:17',
        'total_usd' => null,
        'total_ua' => null,
        'course' => 0,
        'trade_price' => null,
        'start_price' => null,
        'cost_price' => null,
        'date_update' => '2019-05-30 16:38:17',
        'recalculated' => null
    ],
    'emptyConsumption' => [
        'id' => 2,
        'transaction' => 200484,
        'old_value' => null,
        'whence' => 1,
        'where' => 5,
        'prod_value' => null,
        'status' => 0,
        'type' => 2,
        'date' => '2019-05-30 16:48:17',
        'total_usd' => null,
        'total_ua' => null,
        'course' => 30,
        'trade_price' => null,
        'start_price' => null,
        'cost_price' => null,
        'date_update' => '2019-05-30 16:48:17',
        'recalculated' => null
    ],
];